-- Music Bar PostgreSQL schema
-- Import into a new PostgreSQL or Neon database before starting the app.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS playlists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  is_default BOOLEAN NOT NULL DEFAULT false,
  is_enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS playlists_tenant_single_default_idx
  ON playlists (tenant_id, is_default)
  WHERE is_default = true;

-- Songs: deduplicated song metadata keyed by youtube_id
CREATE TABLE IF NOT EXISTS songs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  youtube_id VARCHAR(64) NOT NULL,
  title TEXT NOT NULL,
  thumbnail TEXT,
  duration VARCHAR(64),
  artist TEXT,
  audio_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS songs_youtube_id_idx
  ON songs (youtube_id);

CREATE INDEX IF NOT EXISTS songs_title_idx
  ON songs (title);

CREATE TABLE IF NOT EXISTS playlist_songs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  playlist_id BIGINT NOT NULL REFERENCES playlists(id) ON DELETE CASCADE,
  song_id BIGINT NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS playlist_songs_song_id_idx
  ON playlist_songs (song_id);

CREATE INDEX IF NOT EXISTS playlist_songs_order_idx
  ON playlist_songs (playlist_id, position, created_at);

CREATE TABLE IF NOT EXISTS song_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  song_id BIGINT NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
  requested_by VARCHAR(255),
  device_id VARCHAR(255),
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'playing', 'played', 'skipped')),
  played_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS song_requests_song_id_idx
  ON song_requests (song_id);

CREATE INDEX IF NOT EXISTS song_requests_pending_queue_idx
  ON song_requests (created_at)
  WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS app_settings (
  key VARCHAR(255) PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO app_settings (key, value)
VALUES
  ('admin_pin', '"1234"'::jsonb),
  ('active_playlist_ids', '[]'::jsonb),
  ('is_requests_enabled', 'true'::jsonb)
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS active_players (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id VARCHAR(255) UNIQUE NOT NULL,
  device_name VARCHAR(255) NOT NULL,
  device_type VARCHAR(50) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  last_ping TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS active_players_status_ping_idx
  ON active_players (is_active DESC, last_ping DESC);

COMMIT;
